// <auto-generated />
using System;
using EsFinaleMeteo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EsFinaleMeteo.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("EsFinaleMeteo.Model.DCittà", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Long")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("DCittà");
                });

            modelBuilder.Entity("EsFinaleMeteo.Model.DMeteo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvgT")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PercP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("luogoid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("luogoid");

                    b.ToTable("DatiMeteo");
                });

            modelBuilder.Entity("EsFinaleMeteo.Model.DMeteo", b =>
                {
                    b.HasOne("EsFinaleMeteo.Model.DCittà", "luogo")
                        .WithMany()
                        .HasForeignKey("luogoid");

                    b.Navigation("luogo");
                });
#pragma warning restore 612, 618
        }
    }
}
